theme: jekyll-theme-cayman
title: Standard.Licensing
description: Easy-to-use licensing library for .NET Framework, Mono, .NET Core, and Xamarin products
show_downloads: true
google_analytics: G-15FW9E4X4K
