title: Standard.Licensing
description: Easy-to-use licensing library for .NET Framework, Mono, .NET Core, and Xamarin products
show_downloads: true
show_header: false
google_adsense: ca-pub-1135979461412092
google_analytics: G-MKQK789F6L
theme: jekyll-theme-cayman
